import createClient from "openapi-fetch";

import { API_URL } from "$constants/api";
// Use
/* 
npx openapi-typescript http://127.0.0.1:9000/api/v2/schema/ -o ./src/lib/clients/v2.ts 
*/
import type { paths } from "./v2"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: API_URL, headers: {} });

export default client;
