name: Merge

on: [push]

permissions:
    contents: write
    pull-requests: write

jobs:
    'build-frontend':
        name: Build Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Node.JS
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build



    merge:
        runs-on: ubuntu-latest
        needs: ['build-frontend']
        if: github.actor == 'dependabot[bot]' # Detect that the PR author is dependabot
        steps:
            - uses: actions/checkout@v4
            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

 
